---
title: "Activity log"
author: "Jing Zhao"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  fig.align = 'center',
  message = FALSE, 
  warning = FALSE
  )
```

## Activity Log of UNSIAP Data Visulization E-Learning Course

```{r libraries}
library(stringr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(forcats)

```

### Import data

```{r data}
data_log <- read.csv("Data/logs_DTV20_20210121-1615.csv")

```

### Clean data

```{r}
data_log <- data_log[!(data_log$User.full.name=="Christophe Bontemps" | data_log$User.full.name=="Ni Ni Thein" | data_log$Component=="Recycle bin"),]

```

### Extract number and text from Description
- Extract course ID
```{r}
CourseID <- str_match(data_log$Description, "(?i)\\bcourse with id '?\\s*(\\d+)")[,2]
head(CourseID)
```

- Extract users ID
```{r}
UserID <- str_match(data_log$Description, "(?i)\\buser with id '?\\s*(\\d+)")[,2]
head(UserID)
```

Extract module ID
```{r}
ModuleID <- str_match(data_log$Description, "(?i)\\bcourse module with id '?\\s*(\\d+)")[,2]
head(ModuleID)
```

- New dataframe with extracted ID
```{r}
#CourseID is not added since it means this datavis course
log_new <- data.frame(data_log, ModuleID, UserID)
```


```{r}
# log_new <- data_log %>%
#   select(Description) %>%
#   extract(Description, 'UserID', regex = "([\\d.]+)[^\\d.]", remove = FALSE) %>%
#   mutate(data_log)
```

### Visualize some variables
Number of times the event was conducted
```{r}
log_new %>%
  filter(!is.na(Event.name)) %>%
  count(Event.name) %>%
  mutate(rank = dense_rank(desc(n))) %>% 
  filter(rank <= 20) %>% 
  ggplot()+
  aes(x=reorder(Event.name, -n), y=n)+
  geom_bar(stat='identity')+
  labs(x="Events", y="Number of times", 
       subtitle = paste(length(unique(log_new$Event.name)),"events ( at the time", format(file.info("Data/logs_DTV20_20210121-1615.csv")["mtime"]
                          ,"%Y-%m-%d"),")"))+
  ggtitle("Number of times the event was conducted (top 22 events)")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        plot.title = element_text(hjust = 0.5, size=12),
        panel.background = element_blank(), text = element_text(size=8), 
        axis.line = element_line(colour = "black"), 
        plot.subtitle = element_text(hjust = 0.5, size=8),
        axis.title.y = element_text(size = 10))+
  coord_flip()
  
```

Number of activity events each user engaged (top and bottom users)
```{r}
log_new %>%
  filter(!is.na(UserID)) %>%
  count(UserID) %>%
  mutate(rank = dense_rank(desc(n))) %>% 
  filter(row_number() >= max(row_number()) - 5 | rank <= 5) %>%
  ggplot()+
  aes(x=reorder(UserID, -n), y=n, 
      fill=factor(ifelse(rank <= 5,"Top 5","Bottom 5")))+
      geom_bar(stat='identity')+
  labs(x="Users' ID", y="", fill="",
       subtitle = paste(length(unique(log_new$UserID)),"users ( at the time", format(file.info("Data/logs_DTV20_20210121-1615.csv")["mtime"]
                          ,"%Y-%m-%d"),")"))+
  ggtitle("Number of events each user engaged (top and bottom users)")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        plot.title = element_text(hjust = 0.5, size=12), 
        plot.subtitle = element_text(hjust = 0.5, size=8),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))

```

